### ISSUE TITLE
Validation failed with "please specify a datacenter" error though I have provided correct datacenter name

### ISSUE THREAD

**Issue by miryalasaigoutham** [aws/eks-anywhere#2798]
Hi Team,

While creating the cluster in vSphere, validation failed due to the below error though I gave the correct data centre details.

2022-07-26T23:52:42.307+0530    V0      ❌ Validation failed     {"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed creating library for new template: creating library eks-a-templates: govc: please specify a datacenter\n", "remediation": ""}

Please let me know if I'm making a mistake.

Thanks and Regards
Sai Goutham Miryala

**Comment by miryalasaigoutham** [comment]
But it says Datacenter validated, when I executed create cluster command

>> eksctl anywhere create cluster -f eksa-vsphere-mgmt-cluster.yaml     
Warning: The recommended size of an external etcd cluster is 3 or 5
Warning: VSphereDatacenterConfig configured in insecure mode
Warning: The recommended size of an external etcd cluster is 3 or 5
Performing setup and validations
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
❌ Validation failed     {"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed creating library for new template: creating library eks-a-templates: govc: please specify a datacenter\n", "remediation": ""}
✅ Validate certificate for registry mirror
✅ Create preflight validations pass
Error: validations failed

**Comment by TerryHowe** [comment]
Does your datacenter config look something like:
```
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: tlhowe
spec:
  datacenter: "Datacenter"
  network: "/Datacenter/network/VM Network"
  server: 10.61.250.74
  thumbprint: ""
```

**Comment by vivek-koppuru** [comment]
This might be related to https://github.com/aws/eks-anywhere/issues/2614 and should be resolved in the next release https://github.com/aws/eks-anywhere/pull/2796

**Comment by miryalasaigoutham** [comment]
@vivek-koppuru yes, my vCenter has multiple datacenters

**Comment by miryalasaigoutham** [comment]
@TerryHowe yes, my datacenter config looks similar to what you have mentioned, I tried with both IP and fully qualified domain name but still seeing the same error with both(IP and FQDN)

**Comment by abhinavmpandey08** [comment]
As a workaround, you can try importing and tagging the OVA in vSphere manually. Here are the instructions for that https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-ovas/
Once you have successfully imported the OVA, you can specify the path to this OVA using the [template](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/#template-optional) field in the clusterconfig to skip auto-importing the OVA.

**Comment by miryalasaigoutham** [comment]
It works with the template field. Imported the OVA in vSphere and then used template field in the config file, after which this error seems to be gone
